version: '3.1'

services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: crud-clients
    container_name: crud-clients-db
    volumes:
      - ./mongo:/data/db
